// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siigbhdorhyocdqqazcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaWdiaGRvcmh5b2NkcXFhemNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTM1NTYsImV4cCI6MjA1ODE2OTU1Nn0.NY9gSpMuGSlKekCQ2SlduyWcwtQqtPatLc_2jKifyf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);